const copy = {
  en: {
    title: "Variants & inventory",
    refresh: "Refresh inventory",
    loadError: "Inventory could not be loaded. Retry before making changes.",
    empty: "No variants are recorded for this product.",
    variant: "Variant",
    sku: "SKU",
    stock: "Stock",
    price: "Price",
    status: "Status",
    active: "Active",
    inactive: "Inactive",
    adjust: "Adjust stock",
    delta: "Quantity change",
    reason: "Reason",
    deltaHint:
      "Use a positive number for received stock or a negative number for stock removed.",
    projected: "Estimated stock after this change",
    previewHint:
      "This estimate uses the last loaded stock. The server applies the change atomically to current stock.",
    saved: "Stock adjustment recorded.",
    failed: "The adjustment could not be completed. Your inputs are preserved.",
    uncertain:
      "The result is unconfirmed. Refresh the ledger or retry this exact adjustment; its request key is retained to prevent applying it twice.",
    retry: "Retry same adjustment",
    busy: "Working…",
    invalid: "Choose a variant, a non-zero whole-number change, and a reason.",
    history: "Stock history",
    historyHint: "Latest 100 adjustments, newest first.",
    noHistory: "No stock adjustments are recorded.",
    before: "Before",
    after: "After",
    change: "Change",
    showAll: "Show more history",
    showLess: "Show less history",
    external:
      "This inventory is managed by the connected store. Make changes there, then sync the connection.",
    editFirst: "Save or discard your product edits before adjusting inventory.",
    backorders: "Backorders allowed",
    stopAtZero: "Stop selling at zero",
    create: "Add variant",
    created: "Variant added and opening stock recorded.",
    newTitle: "Variant name",
    variantId: "Variant ID",
    initialStock: "Opening stock",
    stockPolicy: "When out of stock",
    cancel: "Cancel",
    options: "Options",
    optionName: "Option name",
    optionValue: "Option value",
    addOption: "Add option",
    removeOption: "Remove option",
    createHint:
      "The variant is active immediately; the product must still be active to be ordered. Its price is independent of other custom variants.",
    createFailed:
      "The variant could not be added. Check the variant list before retrying if the result is uncertain; reuse the same ID and SKU.",
    optionsInvalid: "Each option needs a unique name and a value.",
  },
  ar: {
    title: "المتغيرات والمخزون",
    refresh: "تحديث المخزون",
    loadError: "تعذر تحميل المخزون. أعد المحاولة قبل إجراء تغييرات.",
    empty: "لا توجد متغيرات مسجلة لهذا المنتج.",
    variant: "المتغير",
    sku: "رمز SKU",
    stock: "المخزون",
    price: "السعر",
    status: "الحالة",
    active: "نشط",
    inactive: "غير نشط",
    adjust: "تعديل المخزون",
    delta: "التغيير في الكمية",
    reason: "السبب",
    deltaHint: "استخدم عددًا موجبًا للمخزون الوارد أو سالبًا للمخزون المسحوب.",
    projected: "المخزون المتوقع بعد التغيير",
    previewHint:
      "يعتمد التقدير على آخر مخزون محمّل. يطبّق الخادم التغيير على المخزون الحالي كوحدة واحدة.",
    saved: "تم تسجيل تعديل المخزون.",
    failed: "تعذر إكمال التعديل. لم تفقد المدخلات.",
    uncertain:
      "النتيجة غير مؤكدة. حدّث السجل أو أعد نفس التعديل؛ يُحفظ مفتاح الطلب لمنع تطبيقه مرتين.",
    retry: "إعادة نفس التعديل",
    busy: "جارٍ التنفيذ…",
    invalid: "اختر متغيرًا وتغييرًا بعدد صحيح غير صفر وسببًا.",
    history: "سجل المخزون",
    historyHint: "أحدث 100 تعديل، الأحدث أولًا.",
    noHistory: "لا توجد تعديلات مخزون مسجلة.",
    before: "قبل",
    after: "بعد",
    change: "التغيير",
    showAll: "عرض المزيد من السجل",
    showLess: "عرض سجل أقل",
    external:
      "يدير المتجر المتصل هذا المخزون. أجرِ التغييرات هناك ثم زامن الاتصال.",
    editFirst: "احفظ تعديلات المنتج أو تجاهلها قبل تعديل المخزون.",
    backorders: "السماح بالطلب عند النفاد",
    stopAtZero: "إيقاف البيع عند النفاد",
    create: "إضافة متغير",
    created: "أُضيف المتغير وسُجّل المخزون الافتتاحي.",
    newTitle: "اسم المتغير",
    variantId: "معرّف المتغير",
    initialStock: "المخزون الافتتاحي",
    stockPolicy: "عند نفاد المخزون",
    cancel: "إلغاء",
    options: "الخيارات",
    optionName: "اسم الخيار",
    optionValue: "قيمة الخيار",
    addOption: "إضافة خيار",
    removeOption: "حذف الخيار",
    createHint:
      "يصبح المتغير نشطًا فورًا؛ يجب أن يكون المنتج نشطًا أيضًا لقبول الطلبات. سعره مستقل عن المتغيرات المخصصة الأخرى.",
    createFailed:
      "تعذرت إضافة المتغير. راجع قائمة المتغيرات قبل المحاولة إذا كانت النتيجة غير مؤكدة، واستخدم نفس المعرّف ورمز SKU.",
    optionsInvalid: "يحتاج كل خيار إلى اسم فريد وقيمة.",
  },
};
export const inventoryCopy = (language: "ar" | "en") => copy[language];
