type SupportedLanguage = "ar" | "en";

const copy = {
  ar: {
    loadError: "تعذر تحميل المحادثات",
    openError: "تعذر فتح المحادثة",
    unexpectedError: "حدث خطأ غير متوقع.",
    replyQueued: "الرد في طريقه للعميل عبر القناة.",
    mediaQueued: "الملف في طريقه للعميل عبر WhatsApp.",
    suggestionReady: "اقتراح مؤسس على بيانات المتجر — راجعه قبل الإرسال.",
    demoMessageArrived: "وصلت رسالة تجريبية جديدة.",
    demoCustomer: "عميل تجريبي",
    avatarFallback: "ع",
    overdue: "متأخرة",
    newMessages: "جديد",
    leadScore: "درجة العميل المحتمل",
    attachedImage: "صورة مرفقة",
    openDocument: "فتح المستند",
    internalNote: "ملاحظة داخلية",
    suggestedProducts: "منتجات مقترحة",
    attachFile: "إرفاق ملف",
    sendFile: "إرسال",
    currency: "ج.م",
    contextTitle: "سياق العميل والمتجر",
    contextLoadError: "تعذر تحميل بعض بيانات العميل والطلبات.",
    selectForContext: "اختر محادثة لعرض سجل العميل وطلباته.",
    customerProfile: "ملف العميل",
    completedOrders: "طلبات مكتملة",
    totalRevenue: "إجمالي الإنفاق",
    purchaseLikelihood: "احتمال الشراء",
    recentOrders: "الطلبات المرتبطة",
    noRelatedOrders: "لا توجد طلبات مرتبطة ضمن قائمة الطلبات الحديثة.",
    recentHistoryHint:
      "من أحدث 200 طلب في المتجر؛ قد لا تظهر الطلبات الأقدم هنا.",
    retryContext: "إعادة تحميل السياق",
    viewCustomer: "فتح ملف العميل",
    viewOrders: "عرض كل الطلبات",
    order: "طلب",
    examples: [
      "عايز سماعة للمذاكرة والمكالمات وميزانيتي 1500 جنيه",
      "ما هي سياسة الاسترجاع؟",
      "الشاحن السريع متوفر؟ وبكام؟",
    ],
  },
  en: {
    loadError: "Conversations could not be loaded",
    openError: "Conversation could not be opened",
    unexpectedError: "An unexpected error occurred.",
    replyQueued: "The reply is on its way through the channel.",
    mediaQueued: "The file is on its way through WhatsApp.",
    suggestionReady:
      "This suggestion is grounded in store data — review it before sending.",
    demoMessageArrived: "A new demo message arrived.",
    demoCustomer: "Demo customer",
    avatarFallback: "C",
    overdue: "Overdue",
    newMessages: "new",
    leadScore: "Lead score",
    attachedImage: "Attached image",
    openDocument: "Open document",
    internalNote: "Internal note",
    suggestedProducts: "Suggested products",
    attachFile: "Attach file",
    sendFile: "Send",
    currency: "EGP",
    contextTitle: "Customer & commerce context",
    contextLoadError: "Some customer or order context could not be loaded.",
    selectForContext:
      "Select a conversation to view customer and order context.",
    customerProfile: "Customer profile",
    completedOrders: "Completed orders",
    totalRevenue: "Total spend",
    purchaseLikelihood: "Purchase likelihood",
    recentOrders: "Related orders",
    noRelatedOrders: "No related orders in the recent order list.",
    recentHistoryHint:
      "From the store’s latest 200 orders; older orders may not appear here.",
    retryContext: "Retry context",
    viewCustomer: "Open customer profile",
    viewOrders: "View all orders",
    order: "Order",
    examples: [
      "I need headphones for studying and calls within an EGP 1,500 budget",
      "What is the return policy?",
      "Is the fast charger available, and how much is it?",
    ],
  },
} as const;

export function inboxCopy(language: SupportedLanguage) {
  return copy[language];
}
