"""Destructive-free PostgreSQL backup/restore drill in an isolated schema."""

from __future__ import annotations

import os
import secrets
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Any

import psycopg
from psycopg import Cursor

CORE_TABLES = (
    "alembic_version",
    "organizations",
    "users",
    "memberships",
    "stores",
    "products",
    "product_variants",
    "inventory_transactions",
    "customers",
    "orders",
    "order_items",
    "background_jobs",
)

EXPECTED_COUNTS = {
    "alembic_version": 1,
    "organizations": 2,
    "users": 2,
    "memberships": 2,
    "stores": 2,
    "products": 3,
    "product_variants": 3,
    "inventory_transactions": 3,
    "customers": 2,
    "orders": 2,
    "order_items": 3,
    "background_jobs": 2,
}

EXPECTED_TENANT_TOTALS = {
    "store-a": "205.00",
    "store-b": "60.00",
}


def _quoted_schema(schema: str) -> str:
    if not schema.startswith("verify_backup_") or not schema.replace("_", "").isalnum():
        raise ValueError("Unsafe verification schema name")
    return f'"{schema}"'


def _qualified(schema: str, table: str) -> str:
    if table not in CORE_TABLES:
        raise ValueError(f"Unexpected verification table: {table}")
    return f"{_quoted_schema(schema)}.{table}"


def _scalar(cursor: Cursor[Any], query: str, params: tuple[Any, ...] = ()) -> Any:
    cursor.execute(query, params)
    row = cursor.fetchone()
    if row is None:
        raise RuntimeError("Verification query returned no rows")
    return row[0]


def create_fixture(cursor: Cursor[Any], schema: str, migration_head: str) -> None:
    """Create representative commerce data inside an isolated schema."""

    quoted = _quoted_schema(schema)
    cursor.execute(f"CREATE SCHEMA {quoted}")
    cursor.execute(
        f"""
        CREATE TABLE {_qualified(schema, "alembic_version")} (
            version_num varchar(64) PRIMARY KEY
        );
        CREATE TABLE {_qualified(schema, "organizations")} (
            id varchar(64) PRIMARY KEY,
            name varchar(160) NOT NULL,
            plan varchar(30) NOT NULL
        );
        CREATE TABLE {_qualified(schema, "users")} (
            id varchar(64) PRIMARY KEY,
            email varchar(320) NOT NULL UNIQUE,
            password_hash varchar(300) NOT NULL
        );
        CREATE TABLE {_qualified(schema, "memberships")} (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            organization_id varchar(64) NOT NULL
                REFERENCES {_qualified(schema, "organizations")}(id),
            user_id varchar(64) NOT NULL REFERENCES {_qualified(schema, "users")}(id),
            role varchar(20) NOT NULL,
            UNIQUE (organization_id, user_id)
        );
        CREATE TABLE {_qualified(schema, "stores")} (
            id varchar(64) PRIMARY KEY,
            organization_id varchar(64) NOT NULL
                REFERENCES {_qualified(schema, "organizations")}(id),
            slug varchar(100) NOT NULL UNIQUE,
            name varchar(160) NOT NULL
        );
        CREATE TABLE {_qualified(schema, "products")} (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            store_id varchar(64) NOT NULL REFERENCES {_qualified(schema, "stores")}(id),
            product_id varchar(64) NOT NULL,
            name varchar(160) NOT NULL,
            stock integer NOT NULL,
            price_numeric numeric(12, 2) NOT NULL,
            UNIQUE (store_id, product_id)
        );
        CREATE TABLE {_qualified(schema, "product_variants")} (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            store_id varchar(64) NOT NULL REFERENCES {_qualified(schema, "stores")}(id),
            product_pk integer NOT NULL REFERENCES {_qualified(schema, "products")}(id),
            variant_id varchar(64) NOT NULL,
            sku varchar(100) NOT NULL,
            stock integer NOT NULL,
            price_numeric numeric(12, 2) NOT NULL,
            UNIQUE (product_pk, variant_id),
            UNIQUE (store_id, sku)
        );
        CREATE TABLE {_qualified(schema, "inventory_transactions")} (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            store_id varchar(64) NOT NULL REFERENCES {_qualified(schema, "stores")}(id),
            product_pk integer NOT NULL REFERENCES {_qualified(schema, "products")}(id),
            variant_pk integer REFERENCES {_qualified(schema, "product_variants")}(id),
            delta integer NOT NULL,
            quantity_before integer NOT NULL,
            quantity_after integer NOT NULL,
            reason varchar(80) NOT NULL,
            idempotency_key varchar(160) NOT NULL,
            UNIQUE (store_id, idempotency_key)
        );
        CREATE TABLE {_qualified(schema, "customers")} (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            store_id varchar(64) NOT NULL REFERENCES {_qualified(schema, "stores")}(id),
            display_name varchar(160) NOT NULL
        );
        CREATE TABLE {_qualified(schema, "orders")} (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            store_id varchar(64) NOT NULL REFERENCES {_qualified(schema, "stores")}(id),
            customer_id integer NOT NULL REFERENCES {_qualified(schema, "customers")}(id),
            status varchar(20) NOT NULL,
            payment_status varchar(20) NOT NULL,
            subtotal_numeric numeric(12, 2) NOT NULL,
            total_numeric numeric(12, 2) NOT NULL,
            idempotency_key varchar(160) NOT NULL,
            UNIQUE (store_id, idempotency_key)
        );
        CREATE TABLE {_qualified(schema, "order_items")} (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            order_id integer NOT NULL REFERENCES {_qualified(schema, "orders")}(id),
            product_pk integer NOT NULL REFERENCES {_qualified(schema, "products")}(id),
            variant_pk integer REFERENCES {_qualified(schema, "product_variants")}(id),
            product_id varchar(64) NOT NULL,
            variant_id varchar(64),
            quantity integer NOT NULL,
            line_total_numeric numeric(12, 2) NOT NULL
        );
        CREATE TABLE {_qualified(schema, "background_jobs")} (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            store_id varchar(64) REFERENCES {_qualified(schema, "stores")}(id),
            job_type varchar(80) NOT NULL,
            payload_json jsonb NOT NULL DEFAULT '{{}}'::jsonb,
            status varchar(20) NOT NULL,
            attempts integer NOT NULL,
            max_attempts integer NOT NULL,
            dedup_key varchar(160) UNIQUE
        );
        """
    )
    cursor.execute(
        f"INSERT INTO {_qualified(schema, 'alembic_version')} (version_num) VALUES (%s)",
        (migration_head,),
    )
    cursor.executemany(
        f"INSERT INTO {_qualified(schema, 'organizations')} (id, name, plan) VALUES (%s, %s, %s)",
        [("org-a", "Tenant A", "growth"), ("org-b", "Tenant B", "growth")],
    )
    cursor.executemany(
        f"INSERT INTO {_qualified(schema, 'users')} (id, email, password_hash) VALUES (%s, %s, %s)",
        [
            ("user-a", "owner-a@example.invalid", "hash-a"),
            ("user-b", "owner-b@example.invalid", "hash-b"),
        ],
    )
    cursor.executemany(
        f"""
        INSERT INTO {_qualified(schema, "memberships")} (organization_id, user_id, role)
        VALUES (%s, %s, %s)
        """,
        [("org-a", "user-a", "owner"), ("org-b", "user-b", "owner")],
    )
    cursor.executemany(
        f"INSERT INTO {_qualified(schema, 'stores')} (id, organization_id, slug, name) "
        "VALUES (%s, %s, %s, %s)",
        [
            ("store-a", "org-a", "tenant-a", "Tenant A Store"),
            ("store-b", "org-b", "tenant-b", "Tenant B Store"),
        ],
    )
    cursor.executemany(
        f"""
        INSERT INTO {_qualified(schema, "products")}
            (id, store_id, product_id, name, stock, price_numeric)
        VALUES (%s, %s, %s, %s, %s, %s)
        """,
        [
            (1, "store-a", "P100", "Tenant A Headset", 8, "95.00"),
            (2, "store-a", "P200", "Tenant A Keyboard", 4, "110.00"),
            (3, "store-b", "P100", "Tenant B Headset", 5, "60.00"),
        ],
    )
    cursor.executemany(
        f"""
        INSERT INTO {_qualified(schema, "product_variants")}
            (id, store_id, product_pk, variant_id, sku, stock, price_numeric)
        VALUES (%s, %s, %s, %s, %s, %s, %s)
        """,
        [
            (1, "store-a", 1, "default", "A-P100", 8, "95.00"),
            (2, "store-a", 2, "default", "A-P200", 4, "110.00"),
            (3, "store-b", 3, "default", "B-P100", 5, "60.00"),
        ],
    )
    cursor.executemany(
        f"""
        INSERT INTO {_qualified(schema, "inventory_transactions")}
            (store_id, product_pk, variant_pk, delta, quantity_before, quantity_after, reason,
             idempotency_key)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
        """,
        [
            ("store-a", 1, 1, -1, 9, 8, "order_reservation", "inv-a-1"),
            ("store-a", 2, 2, -1, 5, 4, "order_reservation", "inv-a-2"),
            ("store-b", 3, 3, -1, 6, 5, "order_reservation", "inv-b-1"),
        ],
    )
    cursor.executemany(
        f"INSERT INTO {_qualified(schema, 'customers')} (id, store_id, display_name) "
        "VALUES (%s, %s, %s)",
        [(1, "store-a", "Customer A"), (2, "store-b", "Customer B")],
    )
    cursor.executemany(
        f"""
        INSERT INTO {_qualified(schema, "orders")}
            (id, store_id, customer_id, status, payment_status, subtotal_numeric,
             total_numeric, idempotency_key)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
        """,
        [
            (1, "store-a", 1, "confirmed", "awaiting_cash", "205.00", "205.00", "order-a"),
            (2, "store-b", 2, "confirmed", "awaiting_cash", "60.00", "60.00", "order-b"),
        ],
    )
    cursor.executemany(
        f"""
        INSERT INTO {_qualified(schema, "order_items")}
            (order_id, product_pk, variant_pk, product_id, variant_id, quantity,
             line_total_numeric)
        VALUES (%s, %s, %s, %s, %s, %s, %s)
        """,
        [
            (1, 1, 1, "P100", "default", 1, "95.00"),
            (1, 2, 2, "P200", "default", 1, "110.00"),
            (2, 3, 3, "P100", "default", 1, "60.00"),
        ],
    )
    cursor.executemany(
        f"""
        INSERT INTO {_qualified(schema, "background_jobs")}
            (store_id, job_type, payload_json, status, attempts, max_attempts, dedup_key)
        VALUES (%s, %s, %s, %s, %s, %s, %s)
        """,
        [
            ("store-a", "channel.send_message", '{"order_id": 1}', "succeeded", 1, 3, "job-a"),
            ("store-b", "content.publish", '{"campaign_id": 2}', "pending", 0, 3, "job-b"),
        ],
    )


def validate_restored_fixture(cursor: Cursor[Any], schema: str, migration_head: str) -> None:
    """Fail if the restored data lost core rows or tenant-scoped relationships."""

    for table, expected_count in EXPECTED_COUNTS.items():
        actual = _scalar(cursor, f"SELECT count(*) FROM {_qualified(schema, table)}")
        if actual != expected_count:
            raise RuntimeError(f"{table} restored {actual} rows; expected {expected_count}")

    restored_head = _scalar(
        cursor,
        f"SELECT version_num FROM {_qualified(schema, 'alembic_version')}",
    )
    if restored_head != migration_head:
        raise RuntimeError(f"Restored migration head {restored_head!r} != {migration_head!r}")

    tenant_totals = {
        store_id: total
        for store_id, total in cursor.execute(
            f"""
            SELECT store_id, total_numeric::text
            FROM {_qualified(schema, "orders")}
            ORDER BY store_id
            """
        ).fetchall()
    }
    if tenant_totals != EXPECTED_TENANT_TOTALS:
        raise RuntimeError(f"Restored order totals mismatch: {tenant_totals}")

    cross_tenant_checks = {
        "store/customer": f"""
            SELECT count(*)
            FROM {_qualified(schema, "orders")} orders
            JOIN {_qualified(schema, "customers")} customers
                ON customers.id = orders.customer_id
            WHERE customers.store_id != orders.store_id
        """,
        "order/product": f"""
            SELECT count(*)
            FROM {_qualified(schema, "order_items")} order_items
            JOIN {_qualified(schema, "orders")} orders
                ON orders.id = order_items.order_id
            JOIN {_qualified(schema, "products")} products
                ON products.id = order_items.product_pk
            WHERE products.store_id != orders.store_id
        """,
        "order/variant": f"""
            SELECT count(*)
            FROM {_qualified(schema, "order_items")} order_items
            JOIN {_qualified(schema, "orders")} orders
                ON orders.id = order_items.order_id
            LEFT JOIN {_qualified(schema, "product_variants")} variants
                ON variants.id = order_items.variant_pk
            WHERE variants.id IS NOT NULL AND variants.store_id != orders.store_id
        """,
        "inventory/product": f"""
            SELECT count(*)
            FROM {_qualified(schema, "inventory_transactions")} inventory
            JOIN {_qualified(schema, "products")} products
                ON products.id = inventory.product_pk
            WHERE products.store_id != inventory.store_id
        """,
        "inventory/variant": f"""
            SELECT count(*)
            FROM {_qualified(schema, "inventory_transactions")} inventory
            LEFT JOIN {_qualified(schema, "product_variants")} variants
                ON variants.id = inventory.variant_pk
            WHERE variants.id IS NOT NULL AND variants.store_id != inventory.store_id
        """,
        "membership/store": f"""
            SELECT count(*)
            FROM {_qualified(schema, "stores")} stores
            JOIN {_qualified(schema, "memberships")} memberships
                ON memberships.organization_id = stores.organization_id
            JOIN {_qualified(schema, "users")} users
                ON users.id = memberships.user_id
            WHERE users.email NOT LIKE (
                'owner-' || right(stores.organization_id, 1) || chr(37)
            )
        """,
    }
    for label, query in cross_tenant_checks.items():
        mismatches = _scalar(cursor, query)
        if mismatches != 0:
            raise RuntimeError(f"Restored tenant boundary failed for {label}: {mismatches}")


def main() -> int:
    database_url = os.getenv("VERIFY_POSTGRES_URL", "").replace(
        "postgresql+psycopg://", "postgresql://", 1
    )
    if not database_url:
        raise RuntimeError("VERIFY_POSTGRES_URL is required")
    migration_head = os.getenv("EXPECTED_MIGRATION_HEAD", "20260902_0030")
    pg_dump = shutil.which("pg_dump")
    pg_restore = shutil.which("pg_restore")
    if not pg_dump or not pg_restore:
        raise RuntimeError("PostgreSQL client tools pg_dump and pg_restore are required")
    schema = f"verify_backup_{secrets.token_hex(6)}"
    with tempfile.TemporaryDirectory() as directory:
        archive = Path(directory) / "verification.dump"
        with (
            psycopg.connect(database_url, autocommit=True) as connection,
            connection.cursor() as cursor,
        ):
            create_fixture(cursor, schema, migration_head)
        try:
            subprocess.run(
                [
                    pg_dump,
                    database_url,
                    "--format=custom",
                    "--no-owner",
                    "--no-acl",
                    f"--schema={schema}",
                    f"--file={archive}",
                ],
                check=True,
            )
            with (
                psycopg.connect(database_url, autocommit=True) as connection,
                connection.cursor() as cursor,
            ):
                cursor.execute(f"DROP SCHEMA {_quoted_schema(schema)} CASCADE")
            subprocess.run(
                [
                    pg_restore,
                    f"--dbname={database_url}",
                    "--no-owner",
                    "--no-acl",
                    str(archive),
                ],
                check=True,
            )
            with (
                psycopg.connect(database_url) as connection,
                connection.cursor() as cursor,
            ):
                validate_restored_fixture(cursor, schema, migration_head)
        finally:
            with (
                psycopg.connect(database_url, autocommit=True) as connection,
                connection.cursor() as cursor,
            ):
                cursor.execute(f"DROP SCHEMA IF EXISTS {_quoted_schema(schema)} CASCADE")
    print("PostgreSQL backup/restore commerce drill passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
